//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_hoa_don_mua
    {
        public int ma_hoa_don { get; set; }
        public int ma_san_pham { get; set; }
        public int so_luong { get; set; }
        public double don_gia { get; set; }
        public double thanh_tien { get; set; }
    
        public virtual hoa_don_mua hoa_don_mua { get; set; }
        public virtual san_pham san_pham { get; set; }
    }
}
