//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoa_don_ban
    {
        public hoa_don_ban()
        {
            this.chi_tiet_hoa_don_ban = new HashSet<chi_tiet_hoa_don_ban>();
        }
    
        public int ma_hoa_don { get; set; }
        public System.DateTime ngay_lap { get; set; }
        public double tong_tien { get; set; }
        public int ma_khach_hang { get; set; }
        public int ma_nhan_vien { get; set; }
    
        public virtual ICollection<chi_tiet_hoa_don_ban> chi_tiet_hoa_don_ban { get; set; }
        public virtual khach_hang khach_hang { get; set; }
        public virtual nhan_vien nhan_vien { get; set; }
    }
}
