//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class loai_san_pham
    {
        public loai_san_pham()
        {
            this.san_pham = new HashSet<san_pham>();
        }
    
        public int ma_loai_san_pham { get; set; }
        public string ten_loai_san_pham { get; set; }
    
        public virtual ICollection<san_pham> san_pham { get; set; }
    }
}
