//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhan_vien
    {
        public nhan_vien()
        {
            this.hoa_don_ban = new HashSet<hoa_don_ban>();
        }
    
        public int ma_nhan_vien { get; set; }
        public string ho_ten { get; set; }
        public string dia_chi { get; set; }
        public string so_dien_thoai { get; set; }
        public string tai_khoan { get; set; }
        public string mat_khau { get; set; }
        public bool trang_thai { get; set; }
        public int phan_quyen { get; set; }
    
        public virtual ICollection<hoa_don_ban> hoa_don_ban { get; set; }
    }
}
