//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class san_pham
    {
        public san_pham()
        {
            this.chi_tiet_hoa_don_ban = new HashSet<chi_tiet_hoa_don_ban>();
            this.chi_tiet_hoa_don_mua = new HashSet<chi_tiet_hoa_don_mua>();
        }
    
        public int ma_san_pham { get; set; }
        public string ten_san_pham { get; set; }
        public double gia_san_pham { get; set; }
        public int so_luong { get; set; }
        public string don_vi_tinh { get; set; }
        public string thong_so_ky_thuat { get; set; }
        public bool tinh_trang { get; set; }
        public int ma_loai_san_pham { get; set; }
    
        public virtual ICollection<chi_tiet_hoa_don_ban> chi_tiet_hoa_don_ban { get; set; }
        public virtual ICollection<chi_tiet_hoa_don_mua> chi_tiet_hoa_don_mua { get; set; }
        public virtual loai_san_pham loai_san_pham { get; set; }
    }
}
